name: Deploy to Production in AWS - Grêmio Brasileirão 2025

on:
  workflow_run:
    workflows: ["CI Pipeline - Grêmio Brasileirão 2025"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    # Deploy para o servidor via SSH
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Login no GitHub Container Registry no servidor
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull da imagem mais recente
          docker pull ghcr.io/pdelfino0/gremio-brasileirao-2025:latest
          
          # Parar containers existentes (sem falhar se não existirem)
          docker compose down 2>/dev/null || docker-compose down 2>/dev/null || true
          
          # Remover imagens antigas para economizar espaço
          docker image prune -f
          
          # Iniciar com a nova imagem
          docker compose up -d 2>/dev/null || docker-compose up -d
          
          # Verificar se os containers estão rodando
          docker ps
          
          echo "Deploy realizado com sucesso em: $(date)"